import 'package:instargram/models/comment.dart';
import 'package:instargram/models/post.dart';

final List<Post> mockPosts = [
  Post(
    username: 'geewonii',
    avatar: 'images/avatar1.jpg',
    images: ['images/post1.jpg', 'images/post2.jpg', 'images/post3.jpg'],
    likeCount: 15200,
    caption: '📸 ',
    commentUser: 'duchuy',
    commentText: 'Love❤️💕',
    date: '7/4/2025',
    likedUsers: ['duchuy', 'skuukzky'],
    likedAvatars: ['images/avatar2.jpg'],
    cmtCount: 15200,
    shareCount: 7400,
    sendCount: 120000,
    comments: [
      Comment(
        avatar: 'images/avatar1.jpg',
        username: 'geewonii',
        time: '2 giờ',
        content: '❤️❤️❤️',
      ),
      Comment(
        avatar: 'images/avatar2.jpg',
        username: 'duchuy',
        time: '1 giờ',
        content: 'Love❤️💕',
      ),
    ],
  ),
  Post(
    username: 'duchuy',
    avatar: 'images/avatar2.jpg',
    images: ['images/photo5.JPG', 'images/photo6.JPG', 'images/t4.jpg'],
    likeCount: 8900,
    caption: '🌿',
    commentUser: 'geewonii',
    commentText: 'Love 💕',
    date: '31/10/2025',
    likedUsers: ['geewonii', 'skuukzky'],
    likedAvatars: ['images/avatar1.jpg'],
    cmtCount: 200,
    shareCount: 70,
    sendCount: 10,
    comments: [
      Comment(
        avatar: 'images/avatar1.jpg',
        username: 'geewonii',
        time: '2 giờ',
        content: '❤️❤️❤️',
      ),
      Comment(
        avatar: 'images/avatar3.jpg',
        username: 'skuukzky',
        time: '1 giờ',
        content: '🔥🔥',
      ),
    ],
  ),
  Post(
    username: 'duchuy',
    avatar: 'images/avatar2.jpg',
    images: ['images/photo5.JPG', 'images/photo6.JPG'],
    videoUrl: 'videos/1.mp4',
    likeCount: 8900,
    caption: '🌿',
    commentUser: 'geewonii',
    commentText: 'Love 💕',
    date: 'Ngày 31 tháng 10, 2025',
    likedUsers: ['geewonii', 'skuukzky'],
    likedAvatars: ['images/avatar1.jpg'],
    cmtCount: 200,
    shareCount: 70,
    sendCount: 10,
    comments: [
      Comment(
        avatar: 'images/avatar1.jpg',
        username: 'geewonii',
        time: '2 giờ',
        content: '❤️❤️❤️',
      ),
      Comment(
        avatar: 'images/avatar3.jpg',
        username: 'skuukzky',
        time: '1 giờ',
        content: '🔥🔥',
      ),
    ],
  ),
];
